---
name: Release

"on":
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.0.1

      - name: Publish to crates.io
        run: cargo publish -v --all-features --token ${{ secrets.CRATES_TOKEN }}
